# s <- $
S100
v0 w0 a10
v1 w0 a10
v2 w0 a10
[./sk/998.ks] /ks k>d d>r /r 300
[./sk/waves.ks] /ks k>d d>r /r 301
[./sk/vowels.ks] /ks k>d d>r /r 302
[./sk/percussion.ks] /ks k>d d>r /r 303
[./sk/dw8k-01.ks] /ks k>d d>r /r 304
[./sk/dw8k-02.ks] /ks k>d d>r /r 305
[./sk/dw8k-03.ks] /ks k>d d>r /r 306
[./sk/dw8k-04.ks] /ks k>d d>r /r 307
[./sk/dw8k-05.ks] /ks k>d d>r /r 308
[./sk/dw8k-06.ks] /ks k>d d>r /r 309
[./sk/dw8k-07.ks] /ks k>d d>r /r 310
[./sk/dw8k-08.ks] /ks k>d d>r /r 311
[./sk/dw8k-09.ks] /ks k>d d>r /r 312
[./sk/dw8k-10.ks] /ks k>d d>r /r 313
[./sk/dw8k-11.ks] /ks k>d d>r /r 314
[./sk/dw8k-12.ks] /ks k>d d>r /r 315
[./sk/dw8k-13.ks] /ks k>d d>r /r 316
[./sk/dw8k-14.ks] /ks k>d d>r /r 317
[./sk/dw8k-15.ks] /ks k>d d>r /r 318
[./sk/dw8k-16.ks] /ks k>d d>r /r 319
[./sk/gm-bass-sub.ks] /ks k>d d>r /r 320
[./sk/gm-chh.ks] /ks k>d d>r /r 321
[./sk/gm-clap.ks] /ks k>d d>r /r 322
[./sk/gm-kick.ks] /ks k>d d>r /r 323
[./sk/gm-ohh.ks] /ks k>d d>r /r 324
[./sk/gm-perc-moog.ks] /ks k>d d>r /r 325
[./sk/gm-snare-chase.ks] /ks k>d d>r /r 326
[./sk/gm-snare.ks] /ks k>d d>r /r 327
[./sk/gm-bass-chase.ks] /ks k>d d>r /r 328
[./sk/gm-bass-emcc2.ks] /ks k>d d>r /r 329
[./sk/gm-bass-ifl.ks] /ks k>d d>r /r 330
[./sk/gm-lead-chase.ks] /ks k>d d>r /r 331
[./sk/gm-lead-ifl.ks] /ks k>d d>r /r 332
[./sk/gm-lead-moog.ks] /ks k>d d>r /r 333
[./sk/gm-pad-chord.ks] /ks k>d d>r /r 334
[./sk/gm-strings-poly.ks] /ks k>d d>r /r 335
[./sk/gm-strings-solina.ks] /ks k>d d>r /r 336
[./sk/gm-vocoder.ks] /ks k>d d>r /r 337
[./sk/gm-arp-seq.ks] /ks k>d d>r /r 338
[./sk/drums-chh.ks] /ks k>d d>r /r 339
[./sk/drums-clap.ks] /ks k>d d>r /r 340
[./sk/drums-clave.ks] /ks k>d d>r /r 341
[./sk/drums-cowbell.ks] /ks k>d d>r /r 342
[./sk/drums-crash.ks] /ks k>d d>r /r 343
[./sk/drums-cymbal.ks] /ks k>d d>r /r 344
[./sk/drums-hitom.ks] /ks k>d d>r /r 345
[./sk/drums-kick.ks] /ks k>d d>r /r 346
[./sk/drums-lotom.ks] /ks k>d d>r /r 347
[./sk/drums-maracas.ks] /ks k>d d>r /r 348
[./sk/drums-midtom.ks] /ks k>d d>r /r 349
[./sk/drums-ohh.ks] /ks k>d d>r /r 350
[./sk/drums-rim.ks] /ks k>d d>r /r 351
[./sk/drums-snare.ks] /ks k>d d>r /r 352
[./sk/drums-tomhi.ks] /ks k>d d>r /r 353
[./sk/drums-tomlo.ks] /ks k>d d>r /r 354
[./sk/drums-tommid.ks] /ks k>d d>r /r 355
[./sk/drums-trigger.ks] /ks k>d d>r /r 356
[./sk/dm-bell.ks] /ks k>d d>r /r 357
[./sk/dm-chh.ks] /ks k>d d>r /r 358
[./sk/dm-clap.ks] /ks k>d d>r /r 359
[./sk/dm-cymbal.ks] /ks k>d d>r /r 360
[./sk/dm-kick-deep.ks] /ks k>d d>r /r 361
[./sk/dm-kick-stomp.ks] /ks k>d d>r /r 362
[./sk/dm-ohh.ks] /ks k>d d>r /r 363
[./sk/dm-perc-clang.ks] /ks k>d d>r /r 364
[./sk/dm-perc-pipe.ks] /ks k>d d>r /r 365
[./sk/dm-rim.ks] /ks k>d d>r /r 366
[./sk/dm-snap.ks] /ks k>d d>r /r 367
[./sk/dm-snare-crack.ks] /ks k>d d>r /r 368
[./sk/dm-snare-metal.ks] /ks k>d d>r /r 369
[./sk/dm-stomp.ks] /ks k>d d>r /r 370
[./sk/dm-tom-hi.ks] /ks k>d d>r /r 371
[./sk/dm-tom-lo.ks] /ks k>d d>r /r 372
[./sk/is-chh.ks] /ks k>d d>r /r 373
[./sk/is-clap.ks] /ks k>d d>r /r 374
[./sk/is-cowbell.ks] /ks k>d d>r /r 375
[./sk/is-crash.ks] /ks k>d d>r /r 376
[./sk/is-cymbal-crash.ks] /ks k>d d>r /r 377
[./sk/is-kick.ks] /ks k>d d>r /r 378
[./sk/is-ohh.ks] /ks k>d d>r /r 379
[./sk/is-perc-sp12.ks] /ks k>d d>r /r 380
[./sk/is-ride.ks] /ks k>d d>r /r 381
[./sk/is-rim.ks] /ks k>d d>r /r 382
[./sk/is-slam.ks] /ks k>d d>r /r 383
[./sk/is-snare-elec.ks] /ks k>d d>r /r 384
[./sk/is-snare.ks] /ks k>d d>r /r 385
[./sk/is-snare-s900.ks] /ks k>d d>r /r 386
[./sk/is-tom-elec.ks] /ks k>d d>r /r 387
[./sk/is-tom-hi.ks] /ks k>d d>r /r 388
[./sk/is-tom-lo.ks] /ks k>d d>r /r 389
[./sk/is-tom-mid.ks] /ks k>d d>r /r 390
[./sk/is-kick-808.ks] /ks k>d d>r /r 391
[./sk/kw-chh.ks] /ks k>d d>r /r 392
[./sk/kw-clap.ks] /ks k>d d>r /r 393
[./sk/kw-kick-electro.ks] /ks k>d d>r /r 394
[./sk/kw-maracas.ks] /ks k>d d>r /r 395
[./sk/kw-ohh.ks] /ks k>d d>r /r 396
[./sk/kw-trigger.ks] /ks k>d d>r /r 397
[./sk/kw-clave.ks] /ks k>d d>r /r 398
[./sk/kw-cowbell.ks] /ks k>d d>r /r 399
[./sk/kw-cymbal.ks] /ks k>d d>r /r 400
[./sk/kw-kick.ks] /ks k>d d>r /r 401
[./sk/kw-snare-rimshot.ks] /ks k>d d>r /r 402
[./sk/kw-snare.ks] /ks k>d d>r /r 403
[./sk/kw-synsonics.ks] /ks k>d d>r /r 404
[./sk/kw-tom-hi.ks] /ks k>d d>r /r 405
[./sk/kw-tom-lo.ks] /ks k>d d>r /r 406
[./sk/kw-tom-mid.ks] /ks k>d d>r /r 407
[./sk/nin-body.ks] /ks k>d d>r /r 408
[./sk/nin-chh.ks] /ks k>d d>r /r 409
[./sk/nin-clap.ks] /ks k>d d>r /r 410
[./sk/nin-cowbell.ks] /ks k>d d>r /r 411
[./sk/nin-crash.ks] /ks k>d d>r /r 412
[./sk/nin-hitom.ks] /ks k>d d>r /r 413
[./sk/nin-kick2.ks] /ks k>d d>r /r 414
[./sk/nin-kick.ks] /ks k>d d>r /r 415
[./sk/nin-lotom.ks] /ks k>d d>r /r 416
[./sk/nin-ohh.ks] /ks k>d d>r /r 417
[./sk/nin-rimshot.ks] /ks k>d d>r /r 418
[./sk/nin-shaker.ks] /ks k>d d>r /r 419
[./sk/nin-snare-ghost.ks] /ks k>d d>r /r 420
[./sk/nin-snare.ks] /ks k>d d>r /r 421
[./sk/nin-tom.ks] /ks k>d d>r /r 422
[./sk/nap-bass-acid.ks] /ks k>d d>r /r 423
[./sk/nap-bass-grind.ks] /ks k>d d>r /r 424
[./sk/nap-bass-sub-dist.ks] /ks k>d d>r /r 425
[./sk/nap-chh-hiss.ks] /ks k>d d>r /r 426
[./sk/nap-chh-tight.ks] /ks k>d d>r /r 427
[./sk/nap-clap-slap.ks] /ks k>d d>r /r 428
[./sk/nap-fm-alarm.ks] /ks k>d d>r /r 429
[./sk/nap-glitch-stutter.ks] /ks k>d d>r /r 430
[./sk/nap-kick-industrial.ks] /ks k>d d>r /r 431
[./sk/nap-kick-thud.ks] /ks k>d d>r /r 432
[./sk/nap-lead-buzz.ks] /ks k>d d>r /r 433
[./sk/nap-lead-scream.ks] /ks k>d d>r /r 434
[./sk/nap-lead-stab.ks] /ks k>d d>r /r 435
[./sk/nap-noise-sweep.ks] /ks k>d d>r /r 436
[./sk/nap-ohh-scrape.ks] /ks k>d d>r /r 437
[./sk/nap-pad-dread.ks] /ks k>d d>r /r 438
[./sk/nap-pad-gravel.ks] /ks k>d d>r /r 439
[./sk/nap-pad-static.ks] /ks k>d d>r /r 440
[./sk/nap-perc-metal.ks] /ks k>d d>r /r 441
[./sk/nap-perc-slam.ks] /ks k>d d>r /r 442
[./sk/nap-perc-zap.ks] /ks k>d d>r /r 443
[./sk/nap-snare-crack.ks] /ks k>d d>r /r 444
[./sk/nap-snare-rim.ks] /ks k>d d>r /r 445
[./sk/nap-tom-low.ks] /ks k>d d>r /r 446
[./sk/nap-tom-mid.ks] /ks k>d d>r /r 447
[./sk/mod-crush-rez.ks] /ks k>d d>r /r 448
[./sk/bell.ks] /ks k>d d>r /r 449
[./998.ks] /ks k>d d>r /r 450
[./999.ks] /ks k>d d>r /r 451
v10 w1 a0 f440 t 0 .25 0 0
y0
[v0 w300 l1] x0
[v0 w301 l1] xa
[v0 w302 l1] xa
[v0 w303 l1] xa
[v0 w304 l1] xa
[v0 w305 l1] xa
[v0 w306 l1] xa
[v0 w307 l1] xa
[v0 w308 l1] xa
[v0 w309 l1] xa
[v0 w310 l1] xa
[v0 w311 l1] xa
[v0 w312 l1] xa
[v0 w313 l1] xa
[v0 w314 l1] xa
[v0 w315 l1] xa
[v0 w316 l1] xa
[v0 w317 l1] xa
[v0 w318 l1] xa
[v0 w319 l1] xa
[v0 w320 l1] xa
[v0 w321 l1] xa
[v0 w322 l1] xa
[v0 w323 l1] xa
[v0 w324 l1] xa
[v0 w325 l1] xa
[v0 w326 l1] xa
[v0 w327 l1] xa
[v0 w328 l1] xa
[v0 w329 l1] xa
[v0 w330 l1] xa
[v0 w331 l1] xa
[v0 w332 l1] xa
[v0 w333 l1] xa
[v0 w334 l1] xa
[v0 w335 l1] xa
[v0 w336 l1] xa
[v0 w337 l1] xa
[v0 w338 l1] xa
[v0 w339 l1] xa
[v0 w340 l1] xa
[v0 w341 l1] xa
[v0 w342 l1] xa
[v0 w343 l1] xa
[v0 w344 l1] xa
[v0 w345 l1] xa
[v0 w346 l1] xa
[v0 w347 l1] xa
[v0 w348 l1] xa
[v0 w349 l1] xa
[v0 w350 l1] xa
[v0 w351 l1] xa
[v0 w352 l1] xa
[v0 w353 l1] xa
[v0 w354 l1] xa
[v0 w355 l1] xa
[v0 w356 l1] xa
[v0 w357 l1] xa
[v0 w358 l1] xa
[v0 w359 l1] xa
[v0 w360 l1] xa
[v0 w361 l1] xa
[v0 w362 l1] xa
[v0 w363 l1] xa
[v0 w364 l1] xa
[v0 w1 l1] xa
y1
[v1 w365 l1] x0
[v1 w366 l1] xa
[v1 w367 l1] xa
[v1 w368 l1] xa
[v1 w369 l1] xa
[v1 w370 l1] xa
[v1 w371 l1] xa
[v1 w372 l1] xa
[v1 w373 l1] xa
[v1 w374 l1] xa
[v1 w375 l1] xa
[v1 w376 l1] xa
[v1 w377 l1] xa
[v1 w378 l1] xa
[v1 w379 l1] xa
[v1 w380 l1] xa
[v1 w381 l1] xa
[v1 w382 l1] xa
[v1 w383 l1] xa
[v1 w384 l1] xa
[v1 w385 l1] xa
[v1 w386 l1] xa
[v1 w387 l1] xa
[v1 w388 l1] xa
[v1 w389 l1] xa
[v1 w390 l1] xa
[v1 w391 l1] xa
[v1 w392 l1] xa
[v1 w393 l1] xa
[v1 w394 l1] xa
[v1 w395 l1] xa
[v1 w396 l1] xa
[v1 w397 l1] xa
[v1 w398 l1] xa
[v1 w399 l1] xa
[v1 w400 l1] xa
[v1 w401 l1] xa
[v1 w402 l1] xa
[v1 w403 l1] xa
[v1 w404 l1] xa
[v1 w405 l1] xa
[v1 w406 l1] xa
[v1 w407 l1] xa
[v1 w408 l1] xa
[v1 w409 l1] xa
[v1 w410 l1] xa
[v1 w411 l1] xa
[v1 w412 l1] xa
[v1 w413 l1] xa
[v1 w414 l1] xa
[v1 w415 l1] xa
[v1 w416 l1] xa
[v1 w417 l1] xa
[v1 w418 l1] xa
[v1 w419 l1] xa
[v1 w420 l1] xa
[v1 w421 l1] xa
[v1 w422 l1] xa
[v1 w423 l1] xa
[v1 w424 l1] xa
[v1 w425 l1] xa
[v1 w426 l1] xa
[v1 w427 l1] xa
[v1 w428 l1] xa
[v1 w429 l1] xa
[v1 w0 l1] xa
y2
[v2 w430 l1] x0
[v2 w431 l1] xa
[v2 w432 l1] xa
[v2 w433 l1] xa
[v2 w434 l1] xa
[v2 w435 l1] xa
[v2 w436 l1] xa
[v2 w437 l1] xa
[v2 w438 l1] xa
[v2 w439 l1] xa
[v2 w440 l1] xa
[v2 w441 l1] xa
[v2 w442 l1] xa
[v2 w443 l1] xa
[v2 w444 l1] xa
[v2 w445 l1] xa
[v2 w446 l1] xa
[v2 w447 l1] xa
[v2 w448 l1] xa
[v2 w449 l1] xa
[v2 w450 l1] xa
[v2 w451 l1] xa
[v2 w0 l1] xa
[v10 n- l1] xa
