#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARTS_DIR="$DIR/.."

# Build the wavegen tool
gcc -O3 -o "$DIR/wavegen" "$DIR/wavegen.c" "$PARTS_DIR/vendor/ksynth/ksynth.c" -I"$PARTS_DIR/vendor/ksynth" -lm

SIZE=4096

function build_bank() {
    local BANK_DIR=$1
    local OUT_FILE=$2
    local PREFIX=$3
    
    echo "// Generated by tools/build_wavetables.sh" > "$OUT_FILE"
    echo "// Do not edit directly." >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
    
    # Sort files numerically if possible
    for f in $(ls "$BANK_DIR"/*.ks 2>/dev/null | sort -V); do
        local BASE=$(basename "$f" .ks)
        # Extract the last two digits, assuming files end with _01, _02 etc.
        local SLOT=$(echo "$BASE" | grep -o -E '[0-9]{2}$')
        if [ -n "$SLOT" ]; then
            local ARRAY_NAME="${PREFIX}_${SLOT}"
            echo "Generating $ARRAY_NAME from $f ..."
            "$DIR/wavegen" $SIZE "$ARRAY_NAME" "$f" >> "$OUT_FILE"
        else
            echo "Warning: skipping $f, filename must end with a 2-digit number."
        fi
    done
    echo "Done generating $OUT_FILE"
}

build_bank "$PARTS_DIR/waves/esq1" "$PARTS_DIR/esq1_waves.h" "WAVE_ESQ1"
build_bank "$PARTS_DIR/waves/drums" "$PARTS_DIR/drums_waves.h" "WAVE_DRUM"

