#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARTS_DIR="$DIR/.."

gcc -O3 -o "$DIR/wavegen" "$DIR/wavegen.c" "$PARTS_DIR/vendor/ksynth/ksynth.c" -I"$PARTS_DIR/vendor/ksynth" -lm

function build_bank() {
    local BANK_DIR=$1
    local OUT_FILE=$2
    local PREFIX=$3
    local EXPECTED_SIZE=$4
    local LIST_NAME=$5
    
    echo "// Generated by tools/build_wavetables.sh" > "$OUT_FILE"
    echo "// Do not edit directly." >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
    
    local META_ITEMS=""
    
    for f in $(ls "$BANK_DIR"/*.ks 2>/dev/null | sort -V); do
        local BASE=$(basename "$f" .ks)
        # Format: slot_name.ks (e.g. 50_esq1_01.ks)
        local SLOT=$(echo "$BASE" | grep -o -E '^[0-9]+')
        local NAME=$(echo "$BASE" | sed -E 's/^[0-9]+_//')
        
        if [ -n "$SLOT" ]; then
            local ARRAY_NAME="${PREFIX}_${SLOT}"
            echo "Generating $ARRAY_NAME (slot $SLOT, name $NAME) from $f ..."
            "$DIR/wavegen" "$SLOT" "$NAME" "$ARRAY_NAME" "$f" "$EXPECTED_SIZE" >> "$OUT_FILE"
            META_ITEMS="${META_ITEMS}    &${ARRAY_NAME}_META,\n"
        else
            echo "Warning: skipping $f, filename must start with a slot number."
        fi
    done
    
    echo "static const static_wave_meta_t* ${LIST_NAME}[] = {" >> "$OUT_FILE"
    echo -e "$META_ITEMS    NULL\n};" >> "$OUT_FILE"
    
    echo "Done generating $OUT_FILE"
}

build_bank "$PARTS_DIR/waves/esq1" "$PARTS_DIR/esq1_waves.h" "WAVE_ESQ1" 4096 "ESQ1_WAVES"
build_bank "$PARTS_DIR/waves/drums" "$PARTS_DIR/drums_waves.h" "WAVE_DRUM" 0 "DRUM_WAVES"
