find_program(ZIG_EXECUTABLE zig REQUIRED)

set(CMAKE_C_COMPILER "${ZIG_EXECUTABLE}" CACHE FILEPATH "Zig executable")
set(CMAKE_C_COMPILER_ARG1 "cc" CACHE STRING "Zig C compiler subcommand")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_AR "${ZIG_EXECUTABLE}" CACHE FILEPATH "Zig executable")
set(CMAKE_RANLIB "${ZIG_EXECUTABLE}" CACHE FILEPATH "Zig executable")

set(CMAKE_C_ARCHIVE_CREATE
    "<CMAKE_AR> ar qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH
    "<CMAKE_RANLIB> ranlib <TARGET>")
