# 2030.sk: LinnDrum 80s Synthwave & Italo-Disco 16-Step Groove
# -------------------------------------------------------------
M 80

# Voice Assignments:
v0 w82 f440 a15          # Kick (Natural unpitched playback)
v1 w83 f440 a20          # Snare
v2 w85 f440 a20          # Open Hat
v3 w89 f440 a15          # Mid Tom
v4 w15 f440 a3 t 0 .25 0 0 G5 H5#
v5 w16 N0,5 a3 t 0 .25 0 0 #

/SS 0 (36 48)

# 16-Step Pattern (Full 4/4 Bar @ 118 BPM)
y0
[v0 l1 v4 n&0 l1] x0          # Beat 1 Kick + Bass C2
[v4 n&0 l0.5] x1              # Chugging Octave C3
[v2 l0.4 v4 n&0 l0.8] x2      # Hat + Bass C2
[v4 n&0 l0.5] x3              # Octave C3
[v0 l1 v1 l1 v4 n&0 l1] x4    # Beat 2 Kick + Linn Snare Crack
[v4 n&0 0.5] x5               # Octave C3
[v0 l0.8 v4 n&0 l0.8] x6      # Kick + Bass C2
[v4 n&0 l0.5] x7              # Octave C3
[v0 l1 v4 n&0 l1] x8          # Beat 3 Kick + Bass C2
[v4 n&0 l0.5] x9              # Octave C3
[v0 l0.8 v4 n&0 l0.8] x10     # Kick + Bass C2
[v4 n&0 l0.5] x11             # Octave C3
[v1 l1 v4 n&0 l1] x12         # Beat 4 Snare Backbeat
[v3 l0.8 z*2 v4 n&0 l0.5] x13 # Mid Tom Double-Tap Fill
[v0 l0.8 v3l0.8] x14          # Kick + Mid Tom
[v3 l0.9 z*2] x15             # Tom Roll Turnaround

# Start Pattern
Z1
